# The URL the site will be built for
base_url = "https://github.com/jbutterwick/prairie.html"

default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = false

[languages]

[languages.en]
title = "prairie"
description = "A clean Zola theme for blogging and projects"
# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [
    { name = "tags", feed = true, lang = "en" },
    { name = "categories", feed = true, lang = "en" },
]

[languages.en.translations]
projects = "Projects"
blog = "Blog"
about = "About"
recent_projects = "Recent Projects"
more_projects = "More Projects"
recent_blog_posts = "Recent Blog Posts"
more_blog_posts = "More blog posts"
tag = "Tag"
tags = "Tags"
to_all_tags = "To all tags"
category = "Category"
categories = "Categories"
to_all_categories = "To all categories"
view_by = "View by"
other = "Other"
minute = "min"
prev_page = "To newer posts"
next_page = "To older posts"
# Customize your post date format. See: https://tera.netlify.app/docs/#date
date_format = "%B %e, %Y"

[extra]
# Development environment. Used by the page macros to load remote content only when in "prod" mode
env = "ZOLA_ENV"

# Color theme mode. Options: light, dark, auto (automatically switch depending on OS/user agent settings)
color_mode = "auto"

# List of Papaya navigational menu items. Used to construct the navigation bar. See the README for item schema.
menu_items = [
    { name = "projects", url = "$LANG_BASE_URL/projects", show_recent = true, recent_items = 3, recent_trans_key = "recent_projects", more_trans_key = "more_projects" },
    { name = "blog", url = "$LANG_BASE_URL/blog", show_recent = true, recent_items = 3, recent_trans_key = "recent_blog_posts", more_trans_key = "more_blog_posts" },
    # tag is not a zola section, it's just a link.
    { name = "tags", url = "$LANG_BASE_URL/tags" },
    { name = "about", url = "$LANG_BASE_URL/about", show_recent = false },
]

[extra.images]
# Width defined in pixels
max_width = 2500

# Open Graph Protocol objects. See: https://ogp.me/
[extra.ogp]
locale = "en_US"
first_name = "prairie"
last_name = "Butterwick"
gender = "male"
username = "jbutterwick"

# Footer social links; full options listed in macros/social.html
[extra.social]
email = "jordan@butterwick.tech"
github = "jbutterwick"
linkedin = "jbutterwick"

# CDN links
[extra.cdn]
font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
