name = "prairie"
description = "A clean Zola theme for blogging and projects"
license = "MIT"
homepage = "https://github.com/jbutterwick/prairie"
# The minimum version of Zola required
min_version = "0.16.1"
# An optional live demo URL
demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
env = "$ZOLA_ENV"
papaya_date_format = "%e %B %Y"
papaya_menu_links = []

[extra.images]

[extra.social]

[extra.ogp]

# The theme author info: you!
[author]
name = "Jordan Butterwick"
homepage = "https://butterwick.tech"
